import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import {
  applyPostgresMigrations,
  convertSqliteMigration,
  identitySequenceSetvalSql,
  SyncPostgresDatabase,
  toPostgresQuery,
} from "./postgres_db.mjs";

test("convertSqliteMigration converts SQLite table defaults and inserts to PostgreSQL", () => {
  const sql = `
    create table if not exists app_user (
      id integer primary key autoincrement,
      username text not null unique,
      created_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
    );

    insert or ignore into app_user_role(user_id, role_id) values (1, 2);

    insert or ignore into rbac_role_permission(role_id, permission_id)
    select role.id, permission.id
    from rbac_role role
    join rbac_permission permission
    where role.role_key = 'ADMIN';
  `;

  const converted = convertSqliteMigration(sql);

  assert.match(converted, /id bigint generated by default as identity primary key/);
  assert.match(converted, /default \(to_char\(\(clock_timestamp\(\) at time zone 'UTC'\)/);
  assert.match(converted, /insert into app_user_role/);
  assert.match(converted, /on conflict \(user_id, role_id\) do nothing/);
  assert.match(converted, /on conflict \(role_id, permission_id\) do nothing/);
  assert.doesNotMatch(converted, /autoincrement/i);
  assert.doesNotMatch(converted, /strftime/i);
  assert.doesNotMatch(converted, /insert or ignore/i);
});

test("convertSqliteMigration preserves json object text storage semantics", () => {
  const converted = convertSqliteMigration(`
    insert into shein_product_bucket(raw_payload_json)
    select json_object('seeded_from', 'listing', 'listing_id', listing.id)
    from listing;
  `);

  assert.match(converted, /json_build_object\('seeded_from', 'listing', 'listing_id', listing\.id\)::text/);
});

test("convertSqliteMigration expands product SKC summary group by columns for PostgreSQL", () => {
  const converted = convertSqliteMigration(`
    create view v_product_skc_summary as
    select
      spu.id as spu_id,
      spu.spu_code,
      spu.spu_name,
      spu.listing_title_cn,
      spu.listing_title_en,
      spu.brand_name,
      skc.id as skc_id,
      skc.skc_code,
      count(sku.id) as sku_count
    from product_skc skc
    join product_spu spu on spu.id = skc.spu_id
    left join product_sku sku on sku.skc_id = skc.id
    group by skc.id;
  `);

  assert.match(converted, /group by\s+spu\.id,\s+spu\.spu_code,\s+spu\.spu_name,\s+spu\.listing_title_cn,\s+spu\.listing_title_en,/);
  assert.match(converted, /skc\.updated_at/);
  assert.doesNotMatch(converted, /group by skc\.id;/i);
});

test("toPostgresQuery converts placeholders and common SQLite runtime functions", () => {
  const query = toPostgresQuery(`
    select
      group_concat(distinct role.role_key) as roles,
      json_extract(raw_payload_json, '$.field_completeness.missing_field_count') as missing_count
    from app_user
    where id = ? and username = ?
  `);

  assert.match(query, /string_agg\(distinct role\.role_key::text, ','\) as roles/);
  assert.match(query, /\(raw_payload_json::jsonb #>> '\{field_completeness,missing_field_count\}'\) as missing_count/);
  assert.match(query, /where id = \$1 and username = \$2/);
});

test("toPostgresQuery leaves question marks inside SQL literals untouched", () => {
  const query = toPostgresQuery(`
    select '?', 'what?', "literal?column"
    from app_user
    where note = 'a ? b'
      and username = ?
      and message = ?
  `);

  assert.match(query, /select '\?', 'what\?', "literal\?column"/);
  assert.match(query, /where note = 'a \? b'/);
  assert.match(query, /and username = \$1/);
  assert.match(query, /and message = \$2/);
  assert.doesNotMatch(query, /'\$[0-9]'/);
  assert.doesNotMatch(query, /what\$[0-9]/);
});

test("toPostgresQuery converts SQLite LIKE comparisons to PostgreSQL case-insensitive comparisons", () => {
  const query = toPostgresQuery(`
    select *
    from product_spu
    where spu_name like ?
      and path not like '%套装%'
      and status = ?
  `);

  assert.match(query, /spu_name ilike \$1/);
  assert.match(query, /path not ilike '%套装%'/);
  assert.match(query, /status = \$2/);
  assert.doesNotMatch(query, /\slike\s/i);
});

test("toPostgresQuery converts SQLite integer casts to safe PostgreSQL numeric casts", () => {
  const query = toPostgresQuery(`
    select *
    from size_conversion_rule
    order by cast(local_size_name as integer), local_size_name
  `);

  assert.match(query, /case\s+when \(local_size_name\) is null then null/i);
  assert.match(query, /when trim\(\(local_size_name\)::text\) ~/i);
  assert.match(query, /then trunc\(substring\(trim\(\(local_size_name\)::text\) from/i);
  assert.match(query, /else 0\s+end,\s+local_size_name/i);
  assert.doesNotMatch(query, /cast\(local_size_name as integer\)/i);
});

test("toPostgresQuery converts runtime insert-or-ignore to conflict do nothing", () => {
  const query = toPostgresQuery(`
    insert or ignore into app_user_role(user_id, role_id)
    values (?, ?)
  `);

  assert.match(query, /insert into app_user_role/);
  assert.match(query, /values \(\$1, \$2\)/);
  assert.match(query, /on conflict \(user_id, role_id\) do nothing/);
});

test("toPostgresQuery converts runtime insert-or-replace to conflict update", () => {
  const query = toPostgresQuery(`
    insert or replace into channel_attribute_value (
      platform, product_type_id, attribute_id, attribute_value_id,
      attribute_value, attribute_value_en, sync_batch_id, updated_at
    )
    values (?, ?, ?, ?, ?, ?, ?, ?)
  `);

  assert.match(query, /insert into channel_attribute_value/i);
  assert.match(query, /values \(\$1, \$2, \$3, \$4, \$5, \$6, \$7, \$8\)/);
  assert.match(query, /on conflict \(platform, product_type_id, attribute_id, attribute_value_id\) do update set/i);
  assert.match(query, /attribute_value = excluded\.attribute_value/);
  assert.match(query, /updated_at = excluded\.updated_at/);
  assert.doesNotMatch(query, /insert or replace/i);
  assert.doesNotMatch(query, /platform = excluded\.platform/);
});

test("toPostgresQuery converts SQLite JSON array aggregation", () => {
  const query = toPostgresQuery(`
    select json_group_array(distinct spu.spu_code) as spus
    from product_spu spu
  `);

  assert.match(query, /jsonb_agg\(distinct spu\.spu_code\)::text as spus/);
});

test("convertSqliteMigration converts SQLite-style join without ON to cross join", () => {
  const converted = convertSqliteMigration(`
    insert or ignore into rbac_role_permission(role_id, permission_id)
    select role.id, permission.id
    from rbac_role role
    join rbac_permission permission
    where role.role_key = 'ADMIN';
  `);

  assert.match(converted, /from rbac_role role\s+cross join rbac_permission permission\s+where role\.role_key = 'ADMIN'/);
  assert.match(converted, /on conflict \(role_id, permission_id\) do nothing/);
});

test("toPostgresQuery converts JSON type and parameter comparisons", () => {
  const query = toPostgresQuery(`
    select *
    from shein_product_bucket
    where json_type(raw_payload_json, '$.weight_scope') is null
      or json_extract(raw_payload_json, '$.weight_scope') = ?
      or cast(coalesce(json_extract(raw_payload_json, '$.field_completeness.missing_field_count'), 0) as integer) > 0
  `);

  assert.match(query, /jsonb_typeof\(raw_payload_json::jsonb #> '\{weight_scope\}'\) is null/);
  assert.match(query, /\(raw_payload_json::jsonb #>> '\{weight_scope\}'\) = \$1::text/);
  assert.match(query, /trunc\(substring\(trim\(\(coalesce\(\(raw_payload_json::jsonb #>> '\{field_completeness,missing_field_count\}'\), '0'\)\)::text\) from/);
  assert.match(query, /else 0\s+end\s+> 0/);
});

test("toPostgresQuery converts SQLite table info pragma", () => {
  const query = toPostgresQuery("pragma table_info(app_user)");

  assert.match(query, /information_schema\.columns/);
  assert.match(query, /table_name = 'app_user'/);
  assert.match(query, /column_name as name/);
});

test("identity sequence sync advances past existing migrated ids", () => {
  const sql = identitySequenceSetvalSql('"public"."shein_package_rule"', '"id"');

  assert.match(sql, /select max\("id"\) from "public"\."shein_package_rule"/);
  assert.match(sql, /case when \(select max\("id"\) from "public"\."shein_package_rule"\) is null then false else true end/);
  assert.doesNotMatch(sql, /,\s*false\s*\)/);
});

test("PostgreSQL migrations reject a new duplicate numeric prefix", async () => {
  const migrationsDir = fs.mkdtempSync(path.join(os.tmpdir(), "listingify-migrations-"));
  fs.writeFileSync(path.join(migrationsDir, "042_first.sql"), "select 1;\n");
  fs.writeFileSync(path.join(migrationsDir, "042_second.sql"), "select 2;\n");
  const client = {
    async query(sql) {
      if (/information_schema\.columns/i.test(sql)) return { rows: [] };
      return { rows: [] };
    },
    release() {},
  };
  const pool = {
    async query(sql) {
      if (/select version from schema_migration/i.test(sql)) return { rows: [] };
      return { rows: [] };
    },
    async connect() {
      return client;
    },
  };

  try {
    await assert.rejects(
      applyPostgresMigrations(pool, migrationsDir),
      /duplicate migration prefix 042/i,
    );
  } finally {
    fs.rmSync(migrationsDir, { recursive: true, force: true });
  }
});

test("PostgreSQL migrations apply 056 follow-up when early 055 is already registered", async () => {
  const migrationsDir = fs.mkdtempSync(path.join(os.tmpdir(), "listingify-migrations-"));
  const followup = fs.readFileSync(path.resolve("db/migrations/056_product_archive_performance_followups.sql"), "utf8");
  fs.writeFileSync(path.join(migrationsDir, "055_product_archive_performance.sql"), "select 55;\n");
  fs.writeFileSync(path.join(migrationsDir, "056_product_archive_performance_followups.sql"), followup);

  const calls = [];
  const client = {
    async query(sql, params) {
      calls.push({ sql, params });
      if (/select version from schema_migration/i.test(sql)) {
        return { rows: [{ version: "055_product_archive_performance.sql" }] };
      }
      if (/information_schema\.columns/i.test(sql)) return { rows: [] };
      return { rows: [] };
    },
    release() {},
  };
  const pool = {
    async connect() {
      return client;
    },
  };

  try {
    const applied = await applyPostgresMigrations(pool, migrationsDir);
    const appliedVersions = calls
      .filter((call) => /insert into schema_migration\(version\)/i.test(call.sql))
      .map((call) => call.params?.[0]);
    const appliedSql = calls.map((call) => call.sql).join("\n");

    assert.deepEqual(applied, ["056_product_archive_performance_followups.sql"]);
    assert.deepEqual(appliedVersions, ["056_product_archive_performance_followups.sql"]);
    assert.match(appliedSql, /add column if not exists import_fingerprint text/);
    assert.match(appliedSql, /ux_product_archive_source_batch_import_fingerprint/);
    assert.match(appliedSql, /create table if not exists product_archive_draft_preparation/);
    assert.match(appliedSql, /create table if not exists product_archive_sync_negative_cache/);
    assert.match(appliedSql, /create table if not exists listing_launch_plan_spu_latest/);
    assert.match(appliedSql, /create table if not exists listing_launch_plan_import_sheet_stat/);
    assert.match(appliedSql, /on conflict \(import_id, sheet_name\) do update/);
    assert.match(appliedSql, /where listing_launch_plan_spu_latest\.import_id < excluded\.import_id/);
    assert.doesNotMatch(appliedSql, /select 55/);
  } finally {
    fs.rmSync(migrationsDir, { recursive: true, force: true });
  }
});

test("synchronous PostgreSQL worker discards a timed-out query before the next request", () => {
  const previousTimeout = process.env.DATABASE_SYNC_TIMEOUT_MS;
  const databaseUrl = process.env.DATABASE_URL
    ?? "postgres://listingify:listingify@localhost:5432/listingify";
  const db = new SyncPostgresDatabase(databaseUrl, { connectionTimeoutMillis: 1000 });

  try {
    process.env.DATABASE_SYNC_TIMEOUT_MS = "50";
    assert.throws(
      () => db.queryRows("select pg_sleep(0.25), 42 as value"),
      /timed out after 50ms/,
    );

    process.env.DATABASE_SYNC_TIMEOUT_MS = "1000";
    assert.deepEqual(db.queryRows("select 99 as value"), [{ value: 99 }]);
  } finally {
    process.env.DATABASE_SYNC_TIMEOUT_MS = "1000";
    db.close();
    if (previousTimeout === undefined) delete process.env.DATABASE_SYNC_TIMEOUT_MS;
    else process.env.DATABASE_SYNC_TIMEOUT_MS = previousTimeout;
  }
});

test("nested synchronous PostgreSQL transactions use savepoints and preserve outer rollback", () => {
  const databaseUrl = process.env.DATABASE_URL
    ?? "postgres://listingify:listingify@localhost:5432/listingify";
  const db = new SyncPostgresDatabase(databaseUrl, { connectionTimeoutMillis: 1000 });

  try {
    db.exec("create temporary table listingify_nested_tx_test(value integer)");
    const outer = db.transaction(() => {
      db.prepare("insert into listingify_nested_tx_test(value) values (?)").run(1);
      db.transaction(() => {
        db.prepare("insert into listingify_nested_tx_test(value) values (?)").run(2);
      })();
      throw new Error("rollback outer transaction");
    });

    assert.throws(outer, /rollback outer transaction/);
    assert.equal(db.prepare("select count(*) as count from listingify_nested_tx_test").get().count, 0);
  } finally {
    db.close();
  }
});
