import assert from "node:assert/strict";
import test from "node:test";
import {
  convertSqliteMigration,
  identitySequenceSetvalSql,
  syncAwait,
  toPostgresQuery,
} from "./postgres_db.mjs";

test("convertSqliteMigration converts SQLite table defaults and inserts to PostgreSQL", () => {
  const sql = `
    create table if not exists app_user (
      id integer primary key autoincrement,
      username text not null unique,
      created_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
    );

    insert or ignore into app_user_role(user_id, role_id) values (1, 2);

    insert or ignore into rbac_role_permission(role_id, permission_id)
    select role.id, permission.id
    from rbac_role role
    join rbac_permission permission
    where role.role_key = 'ADMIN';
  `;

  const converted = convertSqliteMigration(sql);

  assert.match(converted, /id bigint generated by default as identity primary key/);
  assert.match(converted, /default \(to_char\(\(clock_timestamp\(\) at time zone 'UTC'\)/);
  assert.match(converted, /insert into app_user_role/);
  assert.match(converted, /on conflict \(user_id, role_id\) do nothing/);
  assert.match(converted, /on conflict \(role_id, permission_id\) do nothing/);
  assert.doesNotMatch(converted, /autoincrement/i);
  assert.doesNotMatch(converted, /strftime/i);
  assert.doesNotMatch(converted, /insert or ignore/i);
});

test("convertSqliteMigration preserves json object text storage semantics", () => {
  const converted = convertSqliteMigration(`
    insert into shein_product_bucket(raw_payload_json)
    select json_object('seeded_from', 'listing', 'listing_id', listing.id)
    from listing;
  `);

  assert.match(converted, /json_build_object\('seeded_from', 'listing', 'listing_id', listing\.id\)::text/);
});

test("convertSqliteMigration expands product SKC summary group by columns for PostgreSQL", () => {
  const converted = convertSqliteMigration(`
    create view v_product_skc_summary as
    select
      spu.id as spu_id,
      spu.spu_code,
      spu.spu_name,
      spu.listing_title_cn,
      spu.listing_title_en,
      spu.brand_name,
      skc.id as skc_id,
      skc.skc_code,
      count(sku.id) as sku_count
    from product_skc skc
    join product_spu spu on spu.id = skc.spu_id
    left join product_sku sku on sku.skc_id = skc.id
    group by skc.id;
  `);

  assert.match(converted, /group by\s+spu\.id,\s+spu\.spu_code,\s+spu\.spu_name,\s+spu\.listing_title_cn,\s+spu\.listing_title_en,/);
  assert.match(converted, /skc\.updated_at/);
  assert.doesNotMatch(converted, /group by skc\.id;/i);
});

test("toPostgresQuery converts placeholders and common SQLite runtime functions", () => {
  const query = toPostgresQuery(`
    select
      group_concat(distinct role.role_key) as roles,
      json_extract(raw_payload_json, '$.field_completeness.missing_field_count') as missing_count
    from app_user
    where id = ? and username = ?
  `);

  assert.match(query, /string_agg\(distinct role\.role_key::text, ','\) as roles/);
  assert.match(query, /\(raw_payload_json::jsonb #>> '\{field_completeness,missing_field_count\}'\) as missing_count/);
  assert.match(query, /where id = \$1 and username = \$2/);
});

test("toPostgresQuery converts runtime insert-or-ignore to conflict do nothing", () => {
  const query = toPostgresQuery(`
    insert or ignore into app_user_role(user_id, role_id)
    values (?, ?)
  `);

  assert.match(query, /insert into app_user_role/);
  assert.match(query, /values \(\$1, \$2\)/);
  assert.match(query, /on conflict \(user_id, role_id\) do nothing/);
});

test("toPostgresQuery converts runtime insert-or-replace to conflict update", () => {
  const query = toPostgresQuery(`
    insert or replace into channel_attribute_value (
      platform, product_type_id, attribute_id, attribute_value_id,
      attribute_value, attribute_value_en, sync_batch_id, updated_at
    )
    values (?, ?, ?, ?, ?, ?, ?, ?)
  `);

  assert.match(query, /insert into channel_attribute_value/i);
  assert.match(query, /values \(\$1, \$2, \$3, \$4, \$5, \$6, \$7, \$8\)/);
  assert.match(query, /on conflict \(platform, product_type_id, attribute_id, attribute_value_id\) do update set/i);
  assert.match(query, /attribute_value = excluded\.attribute_value/);
  assert.match(query, /updated_at = excluded\.updated_at/);
  assert.doesNotMatch(query, /insert or replace/i);
  assert.doesNotMatch(query, /platform = excluded\.platform/);
});

test("toPostgresQuery converts SQLite JSON array aggregation", () => {
  const query = toPostgresQuery(`
    select json_group_array(distinct spu.spu_code) as spus
    from product_spu spu
  `);

  assert.match(query, /jsonb_agg\(distinct spu\.spu_code\)::text as spus/);
});

test("convertSqliteMigration converts SQLite-style join without ON to cross join", () => {
  const converted = convertSqliteMigration(`
    insert or ignore into rbac_role_permission(role_id, permission_id)
    select role.id, permission.id
    from rbac_role role
    join rbac_permission permission
    where role.role_key = 'ADMIN';
  `);

  assert.match(converted, /from rbac_role role\s+cross join rbac_permission permission\s+where role\.role_key = 'ADMIN'/);
  assert.match(converted, /on conflict \(role_id, permission_id\) do nothing/);
});

test("toPostgresQuery converts JSON type and parameter comparisons", () => {
  const query = toPostgresQuery(`
    select *
    from shein_product_bucket
    where json_type(raw_payload_json, '$.weight_scope') is null
      or json_extract(raw_payload_json, '$.weight_scope') = ?
      or cast(coalesce(json_extract(raw_payload_json, '$.field_completeness.missing_field_count'), 0) as integer) > 0
  `);

  assert.match(query, /jsonb_typeof\(raw_payload_json::jsonb #> '\{weight_scope\}'\) is null/);
  assert.match(query, /\(raw_payload_json::jsonb #>> '\{weight_scope\}'\) = \$1::text/);
  assert.match(query, /cast\(coalesce\(\(raw_payload_json::jsonb #>> '\{field_completeness,missing_field_count\}'\), '0'\) as integer\) > 0/);
});

test("toPostgresQuery converts SQLite table info pragma", () => {
  const query = toPostgresQuery("pragma table_info(app_user)");

  assert.match(query, /information_schema\.columns/);
  assert.match(query, /table_name = 'app_user'/);
  assert.match(query, /column_name as name/);
});

test("identity sequence sync advances past existing migrated ids", () => {
  const sql = identitySequenceSetvalSql('"public"."shein_package_rule"', '"id"');

  assert.match(sql, /select max\("id"\) from "public"\."shein_package_rule"/);
  assert.match(sql, /case when \(select max\("id"\) from "public"\."shein_package_rule"\) is null then false else true end/);
  assert.doesNotMatch(sql, /,\s*false\s*\)/);
});

test("syncAwait times out unresolved synchronous PostgreSQL calls", () => {
  const previous = process.env.DATABASE_SYNC_TIMEOUT_MS;
  process.env.DATABASE_SYNC_TIMEOUT_MS = "1";
  try {
    assert.throws(() => syncAwait(new Promise(() => {})), /timed out after 1ms/);
  } finally {
    if (previous === undefined) delete process.env.DATABASE_SYNC_TIMEOUT_MS;
    else process.env.DATABASE_SYNC_TIMEOUT_MS = previous;
  }
});
