export const METADATA_TABLES = [
  {
    name: "sync_batch",
    columns: [
      "id",
      "source_system",
      "source_object",
      "batch_no",
      "status",
      "started_at",
      "finished_at",
      "source_dir",
      "total_count",
      "success_count",
      "failed_count",
      "manifest_json",
      "created_at",
    ],
    conflictColumns: ["source_system", "source_object", "batch_no"],
    where: "source_system = 'SHEIN' and source_object = 'metadata'",
    orderBy: "id",
    identityColumn: "id",
  },
  {
    name: "channel_store_metadata",
    columns: ["platform", "metadata_key", "sync_batch_id", "payload_json", "updated_at"],
    conflictColumns: ["platform", "metadata_key"],
    where: "platform = 'SHEIN'",
    orderBy: "platform, metadata_key",
  },
  {
    name: "channel_category",
    columns: [
      "platform",
      "category_id",
      "product_type_id",
      "parent_category_id",
      "category_name",
      "root_category_id",
      "root_category_name",
      "level",
      "path",
      "last_category",
      "sync_batch_id",
      "raw_payload_json",
      "updated_at",
    ],
    conflictColumns: ["platform", "category_id"],
    where: "platform = 'SHEIN'",
    orderBy: "platform, category_id",
  },
  {
    name: "channel_publish_standard",
    columns: [
      "platform",
      "standard_scope",
      "category_id",
      "product_type_id",
      "default_language",
      "currency",
      "support_sale_attribute_sort",
      "trace_id",
      "fill_in_standard_json",
      "picture_config_json",
      "raw_payload_json",
      "sync_batch_id",
      "updated_at",
    ],
    conflictColumns: ["platform", "standard_scope", "category_id"],
    where: "platform = 'SHEIN'",
    orderBy: "platform, standard_scope, category_id",
  },
  {
    name: "channel_publish_field",
    columns: [
      "platform",
      "standard_scope",
      "category_id",
      "product_type_id",
      "module",
      "field_key",
      "required",
      "show",
      "sync_batch_id",
      "updated_at",
    ],
    conflictColumns: ["platform", "standard_scope", "category_id", "module", "field_key"],
    where: "platform = 'SHEIN'",
    orderBy: "platform, standard_scope, category_id, module, field_key",
  },
  {
    name: "channel_picture_config",
    columns: [
      "platform",
      "standard_scope",
      "category_id",
      "product_type_id",
      "field_key",
      "is_true",
      "sync_batch_id",
      "updated_at",
    ],
    conflictColumns: ["platform", "standard_scope", "category_id", "field_key"],
    where: "platform = 'SHEIN'",
    orderBy: "platform, standard_scope, category_id, field_key",
  },
  {
    name: "channel_attribute_template",
    columns: [
      "platform",
      "product_type_id",
      "attr_count",
      "required_count",
      "sale_attributes_json",
      "attribute_infos_json",
      "raw_payload_json",
      "sync_batch_id",
      "updated_at",
    ],
    conflictColumns: ["platform", "product_type_id"],
    where: "platform = 'SHEIN'",
    orderBy: "platform, product_type_id",
  },
  {
    name: "channel_attribute",
    columns: [
      "platform",
      "product_type_id",
      "attribute_id",
      "attribute_name",
      "attribute_name_en",
      "attribute_type",
      "attribute_label",
      "attribute_mode",
      "attribute_status",
      "attribute_input_num",
      "data_dimension",
      "values_count",
      "is_required",
      "is_sale_attribute",
      "is_size_attribute",
      "values_json",
      "raw_payload_json",
      "sync_batch_id",
      "updated_at",
    ],
    conflictColumns: ["platform", "product_type_id", "attribute_id"],
    where: "platform = 'SHEIN'",
    orderBy: "platform, product_type_id, attribute_id",
  },
  {
    name: "channel_attribute_value",
    columns: [
      "platform",
      "product_type_id",
      "attribute_id",
      "attribute_value_id",
      "attribute_value",
      "attribute_value_en",
      "is_custom_attribute_value",
      "is_show",
      "is_black",
      "color",
      "raw_payload_json",
      "sync_batch_id",
      "updated_at",
    ],
    conflictColumns: ["platform", "product_type_id", "attribute_id", "attribute_value_id"],
    where: "platform = 'SHEIN'",
    orderBy: "platform, product_type_id, attribute_id, attribute_value_id",
  },
  {
    name: "channel_required_attribute",
    columns: [
      "platform",
      "category_id",
      "product_type_id",
      "attribute_id",
      "attribute_name",
      "attribute_name_en",
      "attribute_type",
      "attribute_label",
      "attribute_mode",
      "attribute_status",
      "attribute_input_num",
      "values_count",
      "sample_values_json",
      "sync_batch_id",
      "updated_at",
    ],
    conflictColumns: ["platform", "category_id", "product_type_id", "attribute_id"],
    where: "platform = 'SHEIN'",
    orderBy: "platform, category_id, product_type_id, attribute_id",
  },
];

export const BUSINESS_TABLES = [
  {
    name: "business_import_batch",
    columns: [
      "id",
      "import_type",
      "file_name",
      "status",
      "total_count",
      "success_count",
      "failed_count",
      "error_message",
      "uploaded_by",
      "created_at",
      "finished_at",
    ],
    conflictColumns: ["id"],
    where: "import_type in ('SIZE_CONVERSION', 'SUPPLY_DISCOUNT', 'PRODUCT_WEIGHT', 'SHEIN_BRAND')",
    orderBy: "id",
    identityColumn: "id",
  },
  {
    name: "size_conversion_rule",
    columns: [
      "id",
      "import_batch_id",
      "platform",
      "local_size_code",
      "local_size_name",
      "shein_size_value",
      "status",
      "note",
      "raw_payload_json",
      "created_at",
      "updated_at",
    ],
    conflictColumns: ["id"],
    where: "platform = 'SHEIN'",
    orderBy: "id",
    identityColumn: "id",
  },
  {
    name: "shein_package_rule",
    columns: [
      "id",
      "rule_name",
      "priority",
      "match_mode",
      "match_keywords_json",
      "package_length_cm",
      "package_width_cm",
      "package_height_cm",
      "package_type",
      "status",
      "note",
      "created_at",
      "updated_at",
    ],
    conflictColumns: ["id"],
    orderBy: "id",
    identityColumn: "id",
  },
  {
    name: "product_weight_import",
    columns: [
      "id",
      "import_batch_id",
      "spu_code",
      "skc_code",
      "sku_code",
      "package_weight_g",
      "raw_payload_json",
      "created_at",
      "updated_at",
      "status",
    ],
    conflictColumns: ["id"],
    where: "coalesce(status, 'ACTIVE') <> 'DELETED'",
    orderBy: "id",
    identityColumn: "id",
  },
  {
    name: "supply_discount_rule",
    columns: [
      "id",
      "import_batch_id",
      "spu_code",
      "discount",
      "multiplier",
      "status",
      "note",
      "raw_payload_json",
      "created_at",
      "updated_at",
    ],
    conflictColumns: ["id"],
    orderBy: "id",
    identityColumn: "id",
  },
  {
    name: "shein_price_config",
    columns: [
      "id",
      "default_discount",
      "usd_exchange_rate",
      "note",
      "created_at",
      "updated_at",
    ],
    conflictColumns: ["id"],
    orderBy: "id",
  },
  {
    name: "shein_brand_rule",
    columns: [
      "id",
      "platform",
      "brand_code",
      "brand_name",
      "local_brand_name",
      "aliases_json",
      "status",
      "note",
      "created_at",
      "updated_at",
    ],
    conflictColumns: ["id"],
    where: "platform = 'SHEIN'",
    orderBy: "id",
    identityColumn: "id",
  },
];
