import { createBrowserRouter, Navigate } from "react-router"
import { ProtectedLayout } from "@/components/layout/protected-layout"
import {
  BatchDetailPage,
  BrandRulesPage,
  CategoryMappingPage,
  DeepDrawContentPage,
  DeepdrawContentDetailPage,
  DeepdrawFieldMappingsPage,
  DeepdrawMetadataPage,
  ImageLibraryDetailPage,
  ImageLibraryPage,
  ImageManagementPage,
  ListingBatchesPage,
  ListingLaunchPlansPage,
  MdmProductDetailPage,
  MdmProductsPage,
  OperationLogsPage,
  PackageRulesPage,
  PlatformIntegrationsPage,
  PrePublishDraftDetailPage,
  PrePublishValidationPage,
  PriceRulesPage,
  ProductArchiveDetailPage,
  ProductArchiveDraftDetailPage,
  ProductArchiveDraftsPage,
  ProductArchivesPage,
  PublishTaskDetailPage,
  PublishTasksPage,
  RouteSuspense,
  SheinAuditStatusPage,
  SheinBarcodeSizePage,
  SheinCompliancePage,
  SheinFinancePage,
  SheinInventoryPage,
  SheinMetadataPage,
  SheinPlatformIdentitiesPage,
  SheinPlatformProductsPage,
  SheinProcurementPage,
  SheinProductsPage,
  SizeConversionPage,
  SyncTasksPage,
  UsersPage,
} from "./router-lazy-pages"

import LandingPage from "@/pages/landing/page"
import LoginPage from "@/pages/login/page"
import DashboardPage from "@/pages/dashboard/page"

export const router = createBrowserRouter([
  { index: true, element: <LandingPage /> },
  { path: "login", element: <LoginPage /> },
  {
    element: <ProtectedLayout />,
    children: [
      { path: "dashboard", element: <DashboardPage /> },
      { path: "listing-batches", element: <RouteSuspense><ListingBatchesPage /></RouteSuspense> },
      { path: "listing-batches/:id", element: <RouteSuspense><BatchDetailPage /></RouteSuspense> },
      { path: "draft-workbench", element: <Navigate to="/pre-publish-validation" replace /> },
      { path: "draft-workbench/:batchId", element: <Navigate to="/pre-publish-validation" replace /> },
      { path: "image-management", element: <RouteSuspense><ImageManagementPage /></RouteSuspense> },
      { path: "shein-products", element: <RouteSuspense><SheinProductsPage /></RouteSuspense> },
      { path: "shein-platform-products", element: <RouteSuspense><SheinPlatformProductsPage view="list" /></RouteSuspense> },
      { path: "shein-platform-products/sites", element: <RouteSuspense><SheinPlatformProductsPage view="sites" /></RouteSuspense> },
      { path: "shein-platform-products/:spuName", element: <RouteSuspense><SheinPlatformProductsPage view="detail" /></RouteSuspense> },
      { path: "shein-operations/barcode-size", element: <RouteSuspense><SheinBarcodeSizePage /></RouteSuspense> },
      { path: "shein-operations/platform-identities", element: <RouteSuspense><SheinPlatformIdentitiesPage /></RouteSuspense> },
      { path: "shein-operations/audit-status", element: <RouteSuspense><SheinAuditStatusPage /></RouteSuspense> },
      { path: "shein-operations/compliance", element: <RouteSuspense><SheinCompliancePage /></RouteSuspense> },
      { path: "shein-operations/procurement", element: <RouteSuspense><SheinProcurementPage /></RouteSuspense> },
      { path: "shein-operations/inventory", element: <RouteSuspense><SheinInventoryPage /></RouteSuspense> },
      { path: "shein-operations/finance", element: <RouteSuspense><SheinFinancePage /></RouteSuspense> },
      { path: "pre-publish-validation", element: <RouteSuspense><PrePublishValidationPage /></RouteSuspense> },
      { path: "pre-publish-validation/:listingId", element: <RouteSuspense><PrePublishDraftDetailPage /></RouteSuspense> },
      { path: "publish-tasks", element: <RouteSuspense><PublishTasksPage /></RouteSuspense> },
      { path: "publish-tasks/:id", element: <RouteSuspense><PublishTaskDetailPage /></RouteSuspense> },
      { path: "category-mapping", element: <RouteSuspense><CategoryMappingPage /></RouteSuspense> },
      { path: "attribute-mapping", element: <Navigate to="/pre-publish-validation" replace /> },
      { path: "size-conversion", element: <RouteSuspense><SizeConversionPage /></RouteSuspense> },
      { path: "package-rules", element: <RouteSuspense><PackageRulesPage /></RouteSuspense> },
      { path: "price-rules", element: <RouteSuspense><PriceRulesPage /></RouteSuspense> },
      { path: "brand-rules", element: <RouteSuspense><BrandRulesPage /></RouteSuspense> },
      { path: "low-rate-list", element: <Navigate to="/price-rules" replace /> },
      { path: "shein-metadata", element: <RouteSuspense><SheinMetadataPage /></RouteSuspense> },
      { path: "product-archives", element: <RouteSuspense><ProductArchivesPage /></RouteSuspense> },
      { path: "product-archives/:spuCode", element: <RouteSuspense><ProductArchiveDetailPage /></RouteSuspense> },
      { path: "product-archive-drafts", element: <RouteSuspense><ProductArchiveDraftsPage /></RouteSuspense> },
      { path: "product-archive-drafts/:draftId", element: <RouteSuspense><ProductArchiveDraftDetailPage /></RouteSuspense> },
      { path: "listing-launch-plans", element: <RouteSuspense><ListingLaunchPlansPage /></RouteSuspense> },
      { path: "deepdraw-field-mappings", element: <RouteSuspense><DeepdrawFieldMappingsPage /></RouteSuspense> },
      { path: "mdm-products", element: <RouteSuspense><MdmProductsPage /></RouteSuspense> },
      { path: "mdm-products/:spuCode", element: <RouteSuspense><MdmProductDetailPage /></RouteSuspense> },
      { path: "deepdraw-content", element: <RouteSuspense><DeepDrawContentPage /></RouteSuspense> },
      { path: "deepdraw-content/:spuCode", element: <RouteSuspense><DeepdrawContentDetailPage /></RouteSuspense> },
      { path: "deepdraw-metadata", element: <RouteSuspense><DeepdrawMetadataPage /></RouteSuspense> },
      { path: "image-library", element: <RouteSuspense><ImageLibraryPage /></RouteSuspense> },
      { path: "image-library/:assetId", element: <RouteSuspense><ImageLibraryDetailPage /></RouteSuspense> },
      { path: "shein-accounts", element: <Navigate to="/platform-integrations" replace /> },
      { path: "platform-integrations", element: <RouteSuspense><PlatformIntegrationsPage /></RouteSuspense> },
      { path: "users", element: <RouteSuspense><UsersPage /></RouteSuspense> },
      { path: "sync-tasks", element: <RouteSuspense><SyncTasksPage /></RouteSuspense> },
      { path: "operation-logs", element: <RouteSuspense><OperationLogsPage /></RouteSuspense> },
    ],
  },
])
